print ("калькулятор")
a = int(input("введите первое число")
b = int(input("введите второе число")
print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} * {b} = {a * b}")
print(f"{a} / {b} = {a / b}")
